linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  cyclop:
    max-complexity: 27
  gocognit:
    min-complexity: 50
  gci:
    sections:
      - standard
      - default
  goheader:
    template: |-
      Copyright 2023-2024 Edixos
      SPDX-License-Identifier: Apache-2.0

linters:
  enable-all: true
  disable:
    - depguard
    - nestif
    - nonamedreturns
    - exhaustruct
    - contextcheck
    - ifshort
    - nosnakecase
    - structcheck
    - varcheck
    - deadcode
    - funlen
    - gochecknoinits
    - lll
    - exhaustivestruct
    - maligned
    - interfacer
    - scopelint
    - golint
    - gochecknoglobals
    - goerr113
    - gomnd
    - paralleltest
    - ireturn
    - testpackage
    - varnamelen
    - wrapcheck
    - gci

service:
  golangci-lint-version: 1.52.2

run:
  skip-files:
    - "zz_.*\\.go$"
    - "_test*.go"