# Default values for nauticus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- Image repository operator
  repository: ghcr.io/edixos/nauticus
  # -- Image Pull Policy
  pullPolicy: IfNotPresent
  # -- Tag of the image of operator
  # @default -- chart version
  tag: ""

kubeRbacProxy:
  image:
    # -- Image repository for rbac proxy
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    # -- Tag of the image of rbac proxy
    tag: v0.13.1

# -- Reference to one or more secrets to be used when pulling images
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# -- Override the default name
nameOverride: ""
# -- Override the default fullname
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations to add to the controller pod.
podAnnotations: {}

# -- podSecurityContext holds pod-level security attributes and common container settings.
podSecurityContext: {}
#  runAsNonRoot: true

# -- securityContext holds container-level security attributes and common container settings.
securityContext: {}
#  allowPrivilegeEscalation: false
#  capabilities:
#    drop:
#      - ALL

# -- customAnnotations to add to resources
customAnnotations: {}

# -- Adds resources limits and request to controller pod.
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  # -- Enable/Disable autoscaling
  enabled: false
  # -- Min replicas
  minReplicas: 1
  # -- Max replicas
  maxReplicas: 100
  # -- CPU Utilization Percentage
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- NodeSelector to apply to the controller pod
nodeSelector:

# -- Toleration to apply to the controller pod
tolerations: []

# -- Affinity to apply to the controller pod
affinity: {}
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: kubernetes.io/arch
#                operator: In
#                values:
#                  - amd64
#                  - arm64
#                  - ppc64le
#                  - s390x
#              - key: kubernetes.io/os
#                operator: In
#                values:
#                  - linux
# ServiceMonitor
serviceMonitor:
  # -- Enable ServiceMonitor
  enabled: false
  # -- Install the ServiceMonitor into a different Namespace, as the monitoring stack one (default: the release one)
  namespace: ''
  # -- Assign additional labels according to Prometheus' serviceMonitorSelector matching labels
  labels: {}
  # -- Assign additional Annotations
  annotations: {}
  # -- Change matching labels
  matchLabels: {}
  # -- Set targetLabels for the serviceMonitor
  targetLabels: []
  endpoint:
    # -- Set the scrape interval for the endpoint of the serviceMonitor
    interval: "15s"
    # -- Set the scrape timeout for the endpoint of the serviceMonitor
    scrapeTimeout: ""
    # -- Set metricRelabelings for the endpoint of the serviceMonitor
    metricRelabelings: []
    # -- Set relabelings for the endpoint of the serviceMonitor
    relabelings: []
