---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nauticus.io
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nauticus.io
  resources:
  - spaces/finalizers
  verbs:
  - update
- apiGroups:
  - nauticus.io
  resources:
  - spaces/status
  verbs:
  - get
  - patch
  - update
