apiVersion: nauticus.io/v1alpha1
kind: Space
metadata:
  labels:
    app.kubernetes.io/name: space
    app.kubernetes.io/instance: space-sample
    app.kubernetes.io/part-of: nauticus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nauticus
  name: space-sample-sa
spec:
  serviceAccounts:
    items:
      - name: azuresql
        annotations:
          azure.workload.identity/tenant-id: "${APPLICATION_OR_USER_ASSIGNED_IDENTITY_TENANT_ID}"