name: Helm Chart

on:
  push:
    branches: [ "*" ]
    tags: [ "helm-v*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
        with:
          version: 3.3.4
      - name: Linting Chart
        run: helm lint ./charts/nauticus
      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.3.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./.github/configs/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct.yaml --lint-conf ./.github/configs/lintconf.yaml
      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          make helm-docs
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
  release:
    if: startsWith(github.ref, 'refs/tags/helm-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.PASS_GHCR_IO }}
          charts_dir: charts
          charts_url: https://edixos.github.io/charts
          owner: edixos
          repository: charts
          branch: gh-pages
          target_dir: .
          commit_username: smileisak
          commit_email: ikaboubi@gmail.com