name: 'Stale Issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b # v7.0.0
        with:
          stale-issue-message: This is stale, but we won't close it automatically, just bare in mind the maintainers may be busy with other tasks and will reach your issue ASAP. If you have any question or request to prioritize this, please reach `#nauticus` on Kubernetes Slack.
          stale-pr-message: This is stale, but we won't close it automatically, just bare in mind the maintainers may be busy with other tasks and will reach your issue ASAP. If you have any question or request to prioritize this, please reach `#nautius` on Kubernetes Slack.
          stale-issue-label: lifecycle/frozen
          stale-pr-label: lifecycle/frozen
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-close: -1  # dont not close issues/prs